on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  # build, test all supported targets
  build-test-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-musl
        toolchain:
          - stable
            # msrv
          - 1.39.0

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.targets }}
      - run: cargo test --locked --workspace --target ${{ matrix.targets }}

  # fmt and clippy on nightly builds
  fmt-clippy-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy
      - run: cargo fmt --all --check
      - run: cargo clippy --target x86_64-unknown-linux-gnu --workspace -- -D warnings
